# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
  "bash",
  "brightnessctl",
  "btop",
  "calcurse",
  "cava",
  "cliphist",
  "cmus",
  "dex",
  "fastfetch",
  "foot",
  "gammastep",
  "git",
  "gnome-keyring",
  "grim",
  "imagemagick",
  "imv",
  "inter-font",
  "lazygit",
  "libnotify",
  "mako",
  "mpv",
  "nemo",
  "neovim",
  "networkmanager-dmenu",
  "newsboat",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "papirus-icon-theme",
  "pavucontrol",
  "pipewire",
  "pipewire-pulse",
  "playerctl",
  "polkit-gnome",
  "ranger",
  "rofi",
  "sed",
  "slurp",
  "sway",
  "swaybg",
  "swayidle",
  "swaylock",
  "tmux",
  "ttf-fira-code",
  "ttf-nerd-fonts-symbols",
  "udiskie",
  "waybar",
  "wireplumber",
  "wl-clipboard",
  "xdg-desktop-portal-wlr",
  "xorg-xwayland",
  "zsh"
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    # "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]
