# --------------------------- #
#    Manager Configuration    #
# --------------------------- #

# Make sure to enter the exact command you use as the normal user!
# That means including 'sudo' or 'doas' or whatever if the command needs it.
# Where you would put items, enter '#:?'.

# Example: add = "sudo apt install #:?"

add = "yay -S #:? -y" # Example: sudo apt install #:?
remove = "yay -Rns #:? -y" # Example: sudo apt remove #:?
sync = "yay -Syy -y" # Example: sudo apt update
upgrade = "yay -Sy -y" # Example: sudo apt upgrade

plural_name = "system packages"

hook_name = "system_packages" # This is used in hooks. (Example: post_system_packages_add)

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

# many_args = BOOL: Can you supply many items as an argument? Example: 'sudo apt install git vim wget'

[config]
many_args = true
